apiVersion: v1
kind: Service
metadata:
  name: house-price-api
  namespace: house-price-prediction
  labels:
    app.kubernetes.io/name: house-price-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: house-price-api
  ports:
    - name: http
      port: 80
      targetPort: http
